#!/bin/bash

sg=$1
if [[ -z $1 ]];then echo -e "\n  Usage: `basename $0` <security grpup ID>\n\n";exit;fi
locate_pass=`dirname $0`
sg_list=`aws ec2 describe-security-groups --group-ids $sg |$locate_pass/json_parser -l |grep 'IpPermissions'|sed -e 's/\["\|\"]\|\"//g' -e 's/\s/,/g' -e 's/,/ /g'`


IpPermissionsIndex=`echo "$sg_list"|grep -w 'IpPermissions'| awk '{print $4}'|uniq`
IpPermissionsEgressIndex=`echo "$sg_list"|grep -w 'IpPermissionsEgress'| awk '{print $4}'|uniq`

echo -e "\n-============== $sg ==============-\n"
echo "################ Inbound ###################";

while read -a line; do 
	pr[4]='';pr[5]='';defis=' - ';Type=""
	pr[1]=`echo  "$sg_list" |grep -w "IpPermissions $line"|egrep -o -w "IpProtocol .*"|awk '{print $2}'|xargs`
	pr[2]=`echo  "$sg_list" |grep -w "IpPermissions $line"|egrep -o -w "FromPort .*"|awk '{print $2}'|xargs`
	pr[3]=`echo  "$sg_list" |grep -w "IpPermissions $line"|egrep -o -w "ToPort .*"|awk '{print $2}'|xargs`
	pr[4]=`echo  "$sg_list" |grep -w "IpPermissions $line"|egrep -o -w "IpRanges .*"|awk '{print $4}'|xargs`
	pr[5]=`echo  "$sg_list" |grep -w "IpPermissions $line"|egrep -o -w 'UserIdGroupPairs.*GroupId.*'|awk '{print $4}'|xargs`
	if [[ ${pr[1]} -eq "-1" && -z ${pr[2]} &&  -z ${pr[3]} ]]; then pr[1]="all";defis="   ";fi
	if [[ ${pr[2]} -eq ${pr[3]} ]]; then pr[3]="";defis="   ";fi
	if [[ ${pr[2]} -eq "-1" ]]; then pr[2]="all";fi
	if [[ ${pr[1]} == "icmp" && ${pr[2]} == "all" ]] 
	  then 
		pr[2]="all"
		pr[3]="n/a"
		Type="type "
	fi

	if [[ ${pr[1]} == "icmp" ]]; then  pr[3]="";defis="   "; Type="type "; fi

	if [[ ${pr[1]} == "tcp" || ${pr[1]} == "udp" ]] 
	  then  
		if [[ ${pr[2]} -eq "0" && ${pr[3]}  -eq "65535" ]]
		  then 
		    pr[2]=""
		    defis="   "
		    pr[3]="all" 
		fi 
	fi

	if [[ -n ${pr[4]} || -n ${pr[5]} ]]; then 
	  header="%-2s %5s %8.8s%1s%-6.6s %4s "
          printf "$header" "$line"  "${pr[1]}" "${Type}${pr[2]}" "$defis" "${pr[3]}" "to:"
          echo -e "${pr[4]} ${pr[5]}"
	else
	  header="%-2s %5s %8.8s%1s%-6.6s %4s "
          printf "$header" "$line"  "${pr[1]}" "${Type}${pr[2]}" "$defis" "${pr[3]}" "to:"
          echo -e "${pr[4]} ${pr[5]}"
	fi
	#echo "=============================================="
		
done <<< "$IpPermissionsIndex"
 
echo;echo "################ Outbound ###################";echo

while read -a line; do
        pr[4]='';pr[5]='';defis=' - ';Type=""
        pr[1]=`echo  "$sg_list" |grep -w "IpPermissionsEgress $line"|egrep -o -w "IpProtocol .*"|awk '{print $2}'|xargs`
        pr[2]=`echo  "$sg_list" |grep -w "IpPermissionsEgress $line"|egrep -o -w "FromPort .*"|awk '{print $2}'|xargs`
        pr[3]=`echo  "$sg_list" |grep -w "IpPermissionsEgress $line"|egrep -o -w "ToPort .*"|awk '{print $2}'|xargs`
        pr[4]=`echo  "$sg_list" |grep -w "IpPermissionsEgress $line"|egrep -o -w "IpRanges .*"|awk '{print $4}'|xargs`
        pr[5]=`echo  "$sg_list" |grep -w "IpPermissionsEgress $line"|egrep -o -w 'UserIdGroupPairs.*GroupId.*'|awk '{print $4}'|xargs`
        if [[ ${pr[1]} -eq "-1" && -z ${pr[2]} &&  -z ${pr[3]} ]]; then pr[1]="all";defis="";fi
	if [[ ${pr[2]} -eq ${pr[3]} ]]; then pr[3]="";defis="   ";fi
        if [[ ${pr[2]} -eq "-1" ]]; then pr[2]="all";fi
        if [[ ${pr[1]} == "icmp" && ${pr[2]} == "all" ]]
          then
                pr[2]="all"
                pr[3]="n/a"
                Type="type "
        fi

        if [[ ${pr[1]} == "icmp" ]]; then  pr[3]="";defis="   "; Type="type "; fi

        if [[ ${pr[1]} == "tcp" || ${pr[1]} == "udp" ]]
          then
                if [[ ${pr[2]} -eq "0" && ${pr[3]}  -eq "65535" ]]
                  then
                    pr[2]=""
                    defis="   "
                    pr[3]="all"
                fi
        fi

        if [[ -n ${pr[4]} || -n ${pr[5]} ]]; then
	  header="%-2s %5s %8.8s%1s%-6.6s %4s "
          printf "$header" "$line"  "${pr[1]}" "${Type}${pr[2]}" "$defis" "${pr[3]}" "to:"
	  echo -e "${pr[4]} ${pr[5]}"
        else
	  header="%-2s %5s %8.8s%1s%-6.6s %4s"
          printf "$header" "$line" "${pr[1]}" "${pr[2]}" "$defis" "${pr[3]}" "to:" 
	  echo -e "${pr[4]} ${pr[5]}"
        fi
        #echo "=============================================="

done <<< "$IpPermissionsEgressIndex"
echo;echo
